### ISSUE TITLE
Suggestions for implied warranty of habitability 

### ISSUE THREAD

**Issue by LemmaLegal** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#103]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `custom error action`
Details | 1. Began Your claims & defenses section
2. Moved on to the implied warranty of habitability and reviewed conditions issues. 
Suggestion: possibly add inadequate trash collection, and for the "structure" option, maybe add examples like unsafe railways / stairs. Broken smoke detectors might also be a good addition.
Variable being sought | `al_custom_error_action`
Package version | `1.0`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
Inadequate trash collection and Broken smoke detectors added
