### ISSUE TITLE
Selecting No to having summons leads to saying I don't know if I have petition

### ISSUE THREAD

**Issue by LemmaLegal** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#106]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `yep file an answer`
Details | When I select NO on the previous page in response to whether I have a copy of the summons and petition, this page states that I selected "I do not know" whether or not I have these documents and advises to file an Answer. My concern is it may result in tenants who haven't been served consenting to personal jurisdiction by filing the Answer.
Variable being sought | `recommend_filing_answer`
Package version | `1.0`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
Change sentence with or to conditional langauga
You said that you got the Summons and Petition by "posting" (taping, stapling or pinning to your door) 
else
You said you did not receive the Summons and Petition at all.

both answer and motion
