### ISSUE TITLE
Add option to say tenant doesn't know LL's address

### ISSUE THREAD

**Issue by LemmaLegal** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#108]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `persons address`
Details | My only concern with this page is I get a lot of tenants who do not have their landlord's address. They either pay rent in a drop box or LL picks it up in person. It might be helpful to include a note that if the tenant does not know LL's address to use the attorney's address.
Variable being sought | `other_parties[0].address.address`
Package version | `1.0`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by miabonardi** [comment]
Are we using a question like this?

```
---
id: your address
question: |
  What is your landlord's address?
fields:
  - I do not know my landlord's address: ll_address_unknown
    datatype: yesno
  - note: |
      **Okay**. You need your landlord's address for many of the forms on
      this website. You can still finish this form but you will need to add
      your landlord's address before you deliver the form.
    show if: ll_address_unknown       
  - Street address: other_parties[0].address.address
    address autocomplete: True
    hide if: ll_address_unknown
  - Unit: other_parties[0].address.unit
    required: False
    hide if: ll_address_unknown    
  - City: other_parties[0].address.city
    hide if: ll_address_unknown  
  - State: other_parties[0].address.state
    hide if: ll_address_unknown  
    code: |
      states_list()
    default: MA      
  - Zip: other_parties[0].address.zip
    required: False
    hide if: ll_address_unknown
validation code: |
  if ll_address_unknown:
    other_parties[0].address.address = "[ Landlord's address ]"
    other_parties[0].address.city = "[ Landlord's city ]"
---
```

**Comment by tobyfey** [comment]
I changed this so that the landlord's address is only needed if the landlord will be served.
