### ISSUE TITLE
none of the service methods are being generated in the signature

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#118]

**Comment by nonprofittechy** [comment]
Toby to check-in with @mnewsted to see if we can use ILAO's code for selecting service method per-party. 

This should maybe go into the Assembly Line question library too.

**Comment by tobyfey** [comment]
Right now, the answer and motion use just the short version of the service, which works but it:
- allows one method of service
- allows only the first plaintiff to be served
- does not fill in service date, always leaves a blank to fill in later
- does not allow tenant to choose to fill in service later

**Comment by tobyfey** [comment]
fixed (although the problems i identified are still the same)
