### ISSUE TITLE
Implement follow-up text/email/reminder feature

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#12]

**Comment by ianeis** [comment]
Tasks (not exhaustive)
Content
Implementation

**Comment by nonprofittechy** [comment]
https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/643

**Comment by ianeis** [comment]
Important dates, how do we calculate those dates

**Comment by miabonardi** [comment]
We have the reminder feature, but am not sure if this references something else @nonprofittechy

**Comment by nonprofittechy** [comment]
I think we only remind people to file their documents the next day right now. We should consider adding in court date reminders if we already have those as dates we know. Possibly a reminder to follow up on discovery.

**Comment by tobyfey** [comment]
Testing the eviction interview on 6/25, said the hearing date was 6/28
Added updating or adding reminders to the documentation

**Comment by KelizaMcGuire** [comment]
#627
