### ISSUE TITLE
Create ALKiln automated tests

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#122]
1. A "happy path" through the interview
2. Check for regressions on some of the most important bugs

Edit: here's the documentation: https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/automated_integrated_testing

**Comment by nonprofittechy** [comment]
@miabonardi is this something you'd be interested in willing to get up to speed on?

**Comment by miabonardi** [comment]
> @miabonardi is this something you'd be interested in willing to get up to speed on?

Yes. Let me know where to start.

**Comment by miabonardi** [comment]
#161

**Comment by miabonardi** [comment]
https://docs.google.com/presentation/d/165JJAj9w2YrXeifpyvHXTMUxr7u6UDvnCoYy1xvfdhU/edit#slide=id.g22a0a0fc255_0_577

https://www.youtube.com/playlist?list=PLy6i9GFGw5Gwg80yImRuipl38JB2bfxmV
