### ISSUE TITLE
interview order about rent payment awkward

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#152]
the order

-have you paid the rent?
-can you pay the rent?
-have you tried to pay the rent?

is awkward

Should we ask about trying to pay the rent if somebody says they have paid the rent?

**Comment by tobyfey** [comment]
What if we tried to simply the questions - ask about rent attempts - if landlord didn't refuse them, then they are payments.

**Comment by miabonardi** [comment]
The order is now: 
1. Did you try to pay the rent?
2. Have you paid at least part of the rent your landlord says you owe?
3. Can you pay

Closing this issue.
