### ISSUE TITLE
redundant question - petition must not specify months owed if it doesn't state rent

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#153]
id: petition requirements - periods due

asks about if petition specifies months owed after user said petition doesn't state rent at all

**Comment by miabonardi** [comment]
It seems to me you've resolved this here, but I will wait on you to close this issue:

**Comment by tobyfey** [comment]
Tested and works correctly - rent periods question is only asked if petition states rent
