### ISSUE TITLE
Font in names in Caption looks wrong

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#160]

**Comment by nonprofittechy** [comment]
@tobyfey do you want me to put you directly in touch with Georgiana to resolve this?

**Comment by tobyfey** [comment]
@nonprofittechy I just saw this, but I fixed it, if I didn't mess anything else up.  The problem was that the names in the caption were in the Heading 1 Style, which didn't pass through the doc conversion.  I changed it to normal text and then made it the right font, bold and indentation, and it worked.
