### ISSUE TITLE
Some ideas for how to triage Unlawful Detainer from Nonpayment of Rent cases (taken from MADE)

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#166]
![image](https://user-images.githubusercontent.com/7645641/233484422-1e3ea49d-309b-48e2-9c5c-75e2b22c08ae.png)

![image](https://user-images.githubusercontent.com/7645641/233484354-d18a6290-2fe3-4be3-aaa0-040788652059.png)

**Comment by tobyfey** [comment]
#185
