### ISSUE TITLE
Update `id: eviction motion to continue review screen`

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#170]
- True/False answers should be Yes/No
 - Variable names showing as answers

**Comment by tobyfey** [comment]
@miabonardi do you have an example of variable names showing as answers?  In the  "Problems Landlord Failed to Repair"/"Harassment and other breaches of quiet enjoyment"/"Other Landlord Violations" sections?

**Comment by nonprofittechy** [comment]
I'm guessing this is "options" in multiple choice lists that are showing as the internal name instead of the option name.

That's an annoying Docassemble thing. My usual workaround is to create a DAContext object for the choices.

**Comment by miabonardi** [comment]
![Screen Shot 2023-05-24 at 12 11 14 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/6fbbfcfa-6582-4588-b14b-959d7ad57aa2)

Add bullet for other parties

**Comment by miabonardi** [comment]
#202

**Comment by miabonardi** [comment]
1. Change question id to not refer to motion to continue (confusing)
2. Information about the other party did not appear
3. Remove "You may be able to pay and stop the eviction" (scary to see "No")
![Screen Shot 2023-06-21 at 3 43 10 PM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/4917ccc8-1f40-4b8e-aa29-ecf63af6b7fd)

**Comment by miabonardi** [comment]
Inconsistent punctuation on review
![Uploading Screen Shot 2023-06-21 at 3.47.19 PM.png…]()
