### ISSUE TITLE
`id: Information about the original hearing` Make image larger

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#173]
Make MOSummonsCourtDate.png bigger. Tester had to zoom in to view

https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/blob/7b0a52ed846fb0abebac7b600ca755705f422ec7/docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml#L658

**Comment by tobyfey** [comment]
include in #190
