### ISSUE TITLE
Update false promise template 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#175]
Confusion whether a false promise must be verbal

https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/blob/7b0a52ed846fb0abebac7b600ca755705f422ec7/docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml#L193

**Comment by miabonardi** [comment]
If in contract --> breach
If not in contract --> Fraudulent inducement 

Can be either oral or written

**Comment by tobyfey** [comment]
I added a sentence about written promises, but do we want to add another defense about landlord breach?

**Comment by miabonardi** [comment]
@tobyfey is this still open?

**Comment by miabonardi** [comment]
`defense_fraud_lease` covers this
