### ISSUE TITLE
Define fair amount above questions or on hover

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#177]
Tester was confused what fair amount was but didn't see it was defined until after answering question

https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/blob/7b0a52ed846fb0abebac7b600ca755705f422ec7/docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml#L360-L377

**Comment by tobyfey** [comment]
#197

**Comment by tobyfey** [comment]
I talked about this with Shawn, and he said there isn't really much better clarification.  I have these notes from a conversation with Roger Dyer

  liquidated damages - anything more than $5 per day (different in different counties) - it's so ingrained around here
    - if the lease calls for a late fees
i added a sentence - In some counties, more than $5 per day is considered too high.
