### ISSUE TITLE
Add question help text to options 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#178]
How to check for each option
Is there a way to do so in case.net?

https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/blob/7b0a52ed846fb0abebac7b600ca755705f422ec7/docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml#LL1503C22-L1503C22

**Comment by tobyfey** [comment]
combined with #216
