### ISSUE TITLE
Update side navigation bar

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#183]
Case.net on side menu bar is out of place/not tracking right

**Comment by bigbrain550** [comment]
Oops

**Comment by tobyfey** [comment]
I moved Casenet up one space, so now it works more smoothly if the petition is available.  If the petition isn't available, we ask about Casenet right away, so it still jumps to Casenet and then back (we may want to rearrange that section).
