### ISSUE TITLE
Email to send documents did not work

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#184]

**Comment by miabonardi** [comment]
@nonprofittechy this is an interesting issue that has happened on two user tests with this interview

**Comment by miabonardi** [comment]
@nonprofittechy this is still an issue here. I know we are using AL. Confused why this isn't working.

**Comment by tobyfey** [comment]
i received an email after quinten fixed the api
