### ISSUE TITLE
Make `other_parties[0].attorney[0].address` not required 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#187]
- Might not be readily available
- User tester said they would like to know why this information was being asked

**Comment by tobyfey** [comment]
Whoever serves this, you need to show the manner of service
 - Serve the attorney
 - For

Move collection of the address to after service
-add both case.net and summons guide

**Comment by miabonardi** [comment]
![Screen Shot 2023-05-19 at 3 18 52 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/7f1f7fdb-f614-48bd-a5fd-b9ff8f1fab0a)

**Comment by miabonardi** [comment]
Attorney name and address will be on summons and petition

Best to use summons and petition info as most up to date 

If tenant lost forms, use case.net

**Comment by tobyfey** [comment]
when doing #190
make docket and summons question versions for 
id: Landlord representation
id: Opposing Attorney name from Docket

Add Landlord Address question and docket and summons question version

**Comment by tobyfey** [comment]
I made this field required if needed for service.  Also added an explanation saying that the attorney must be served if there is one.
