### ISSUE TITLE
stuck on unlawful detainer kick out

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#189]
button doesn't seem to be setting code

getting rid of the label fixed the problem, but removed the distinction between landlord and tenant.  but in this screen, i think "I" should refer to the user, whether it's an attorney or tenant.  (Another example is the question that asks if the complaint is next to you (doesn't matter if it's an attorney or tenant, whoever is using the interview should have the complaint next to them)

**Comment by tobyfey** [comment]
https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/commit/7383135b5dc4a843a6500f9070d245fc32fd1c9e

**Comment by miabonardi** [comment]
@tobyfey still open?

**Comment by tobyfey** [comment]
The button "I understand, let me keep going" now works, but I got rid of the language an attorney would see, "the tenant understands, let the tenant keep going"

The exit button doesn't do anything.

Fixed the exit button - was timing out because the exit url was wrong - changed all motenantassistance.org to motenanthelp.org
