### ISSUE TITLE
BUG? `id: landlord lied` and `id: petition requirements - rent amount`

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#196]
1. On `id: landlord lied` tester answered `false_promises.there_are_any` as `True` and then `false_promises[0]` as “he’d install smoke detectors” and then on `id: false promises there is another` that `false_promises.there_is_another` is `False`
2. Proceeded through interview
3. Then on `id: petition requirements - rent amount` tester’s input from `false_promises[0]` appeared on screen (almost as an autofill input?) for `rent_amount_owed` which is `datatype: currency` ?

Video recording also available

![Screen Shot 2023-05-24 at 3 06 03 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/6ce507ca-7d96-4c8f-bf63-c1d2c6fe1a8d)

**Comment by tobyfey** [comment]
I think this is a browser issue.  It looks like she is using Chrome.

**Comment by miabonardi** [comment]
@nonprofittechy what do you think

**Comment by nonprofittechy** [comment]
Agree with Toby that this is likely auto-filled from Chrome
