### ISSUE TITLE
`id: late fees` refinement

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#197]
- Tester did not know how much “interest the money could earn in a bank,” or “The cost of the landlord’s time to handle the late payment,” so did not find current guidance helpful
- Consider adding a percentage range for interests and what a late fee typically would be? What percentage of rent is typical for a late fee?

**Comment by tobyfey** [comment]
Is the tenant’s rent more than a fair amount to cover the landlord’s cost? doesn't make sense

**Comment by miabonardi** [comment]
> Is the tenant’s rent more than a fair amount to cover the landlord’s cost? doesn't make sense

Just wants more guidance on late fee

**Comment by tobyfey** [comment]
Added $5 per day example
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/028f31bc-b201-4483-bd4c-9a9f91e23ba9)
