### ISSUE TITLE
Update Answer

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#199]
- Variable names instead of inputes showing up in answer
- “Estopped” not plain language (page 2)
- Tester was very confused why the defenses said “There is no landlord-tenant relationship between parties” because they said there was a lease. 
- `id: relied on promise` tester answered `False` but on Answer under “Landlord’s fraudulent promises induced Tenant to enter the lease” it said “Without this statement Defendant would not have entered into the lease.”

**Comment by miabonardi** [comment]
![Screen Shot 2023-05-24 at 5 06 43 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/c498b8de-3c9b-4efc-936a-6f7f9e1de778)

**Comment by miabonardi** [comment]
Inconsistent capitalization

![Screen Shot 2023-05-24 at 5 07 58 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/44d3a78b-36cc-40cd-bc86-da1c6aec5e3c)

**Comment by miabonardi** [comment]
As mentioned in #200 we should be more clear that these documents are incomplete and user still must do service, date, and sign the answer and motion. @nonprofittechy Moreover, should we be populating user's signature on the answer if they have not yet done service? I just think we should be consistent for both motion and answer unless there are different rules for them? 
![Screen Shot 2023-05-24 at 5 12 34 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/db9c78d6-b387-4ec5-b2c5-9c308c3b8d80)

**Comment by tobyfey** [comment]
I think the problem with the false promises is in the logic, which for some reason requires that relied_on_false_promises is false:
```
  if len(false_promises) > 0 and not relied_on_false_promises:
    defense_fraud_lease = True
  else:
    defense_fraud_lease = False
```
I think the reliance on the false promises is required, and so the defense shouldn't have been applicable at

**Comment by tobyfey** [comment]
made these changes or opened new issues
