### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#2]

**Comment by nonprofittechy** [comment]
Err on keeping discovery minimal because judge might think the tenant doesn't need it.

**Comment by nonprofittechy** [comment]
Motion to expedite or delay hearing until discovery is complete.

**Comment by miabonardi** [comment]
Removing Discovery from September milestone as discussed

**Comment by miabonardi** [comment]
- basis for motion to continue 
- potential for responses
- but may not get responses

**Comment by miabonardi** [comment]
Potentially add requests for admission?
