### ISSUE TITLE
Update Motion to Continue 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#200]
Why are the certificates of service different for the motion and answer? 

If they have to be different, we should at least make sure the one in motion to continue is on 1 page and probably move "[date served]" to after the fill in line. The signature line for the defendant is off and it should be made clear they need to select one of the lines. 

I think most of all, on the download and in the instructions we should be clear in instructing that *this form is not complete or ready to file until service is made and this portion is filled out*.

![Screen Shot 2023-05-24 at 5 00 02 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/8a392a33-564c-4689-aee7-1a9bff32e780)

**Comment by tobyfey** [comment]
made this change
