### ISSUE TITLE
Refactor Court Selector Tool

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#207]
- Use the Assembly Line model with court info Terry sent over
- Refactor the current way court lists work. It's a few separate lists in the YAML now

**Comment by tobyfey** [comment]
Picking the court is the same as picking the county, so do we need to do anything beyond what we're doing to pick the county?  I can add the court information to county_dictionary, so we could show or use the address.

**Comment by miabonardi** [comment]
- Would be better to have all this info in court_information.yml in a spreadsheet (preliminary one attached)
[Courts-Grid view (2).csv](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/files/12752982/Courts-Grid.view.2.csv)

- Using `county_dictionary[trial_court.county][' court_address_and_operating_hours']` for now to reference court info but updating to AL model would make it much more flexible. Currently the formatting is just a single uncontrollable line (see screenshot attached)
![Screen Shot 2023-09-28 at 2 44 46 PM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/3184d61d-b4ab-4626-9137-ab12aeb138d7)


- Consider that it is used for court selector and casenet path when updating

**Comment by KelizaMcGuire** [comment]
Closing because court dictionary and selection based on the defendant's county has been implemented.
