### ISSUE TITLE
`id: estoppel_breaches`

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#216]
Did the landlord violate other laws?  There should be and I don’t know section and advice to contact local housing authority to request an inspection

**Comment by miabonardi** [comment]
Add help text to this page. User tester said most people would not know how to answer here / which housing conditions violate state/local laws etc.

**Comment by tobyfey** [comment]
I think the page titled "Did your landlord violate other laws" would be confusing to a layperson. Some thoughts on changes--

    Be more specific than "other laws." Maybe something like housing codes and municipal ordinances since that's what the questions seem to be getting at?  
        Would like to hash this out in a session. Please set up a way to go over this portion of interview and we can consider if it can be made clearer.

**Comment by tobyfey** [comment]
There is no "I don't know" option for these questions. Consider adding an option.

from St. Jean, Victoria C. <vcstjean@lsem.org> email

**Comment by tobyfey** [comment]
#322
