### ISSUE TITLE
`other_parties.there_is_another`

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#220]
Consider adding image of summons/petition plaintiff box

**Comment by tobyfey** [comment]
there is an image for other_parties.there_is_another, but no image when asking who the second party is

**Comment by tobyfey** [comment]
And there is no image for other_parties.there_is_another the second time it is asked (though this seems intentional)

**Comment by tobyfey** [comment]
Above comments are for users.there_is_another - no picture for users.there_is_another

**Comment by tobyfey** [comment]
image exists if casenet and no pleading
