### ISSUE TITLE
`is_rent_subsidized`

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#221]
Separate "Do you get a rent subsidy or do you live in public housing?" into two separate yesnoradio questions. 

User considered this two separate questions and it was not immediately clear that if user could answer yes to either question we expected the user to answer yes.

**Comment by tobyfey** [comment]
The first question is intended to be something like "Do you live in subsidized housing, including getting a rent subsidy or living in public housing?"
And then if you answer yes, it asks a more specific question about type of subsidized housing.

**Comment by miabonardi** [comment]
> The first question is intended to be something like "Do you live in subsidized housing, including getting a rent subsidy or living in public housing?"
> And then if you answer yes, it asks a more specific question about type of subsidized housing.

Maybe just rephrase then?
