### ISSUE TITLE
Interview order

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#222]
Consider moving `users.there_is_another` sooner

**Comment by tobyfey** [comment]
Moved users.gather() after other_parties.gather() in
interview order, docket review order, interview_order_eviction_motion_to_continue

**Comment by miabonardi** [comment]
Not sure this is the best solution. Is it now asking for plaintiff/other party information first and then user/defendant? The issue was just that users.there_is_another came much later in the interviewer after other party was collected etc. It seemed like an error?
