### ISSUE TITLE
geocode failing, not finding county

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#223]
When I put in an address outside of the City of St. Louis, the interview says that the county couldn't be determined.  In the variables, the address does not have a county and it says geolocate_success is False.

#66

**Comment by tobyfey** [comment]
#116 was about the wrong variable used in the document.  We have that kind of county stuff cleaned up and fixed, the problem with this is just that geolocate isn't identifying counties.  Also, don't know if this is relevant, but before it stopped working altogether, it never seemed to work for addresses in Kansas City.

**Comment by nonprofittechy** [comment]
We just didn't have the proper API setup on either lemmalegal dev or the motenanthelp production server
