### ISSUE TITLE
formatting for lists in documents

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#228]
I changed it so that lists (like the lists of conditions problems, quiet enjoyment breaches, estoppel breaches) have an ", and" at the end of each line except for the last one in the list.  I'm not sure if this is what we want.
   
           ![Screen Shot 2023-05-24 at 5 06 43 PM](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/assets/65858862/c498b8de-3c9b-4efc-936a-6f7f9e1de778)

_Originally posted by @miabonardi in https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/issues/199#issuecomment-1561927244_

**Comment by nonprofittechy** [comment]
Don't think the word "and" is helpful, but we should use list formatting and indentation. List level 1 should be numbered, list 2 letters (a, b, c, etc.). Just using the normal Word list indentation levels.

**Comment by tobyfey** [comment]
#256
