### ISSUE TITLE
Fix permanent links for the "learn" pages

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#267]
Several say "learns" in the URL instead of "learn/".

Also at least one page says "test" in the URL: https://motenanthelp.org/learns/test-12/

**Comment by tobyfey** [comment]
i edited the post type to get rid of the plural - changed both Plural Label and Custom Rewrite Slug, but then the learn page would no longer show up.  Maybe a problem if there are categories and posts of the same name?

Is this a problem?

**Comment by tobyfey** [comment]
fixed the test, but learns as plural is intentional
