### ISSUE TITLE
Remove references to GBLS/MADE

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#277]
https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/blob/f3f7c54715a30979f0e0dcf3e47c1b928529f0ec/docassemble/MOHUDEvictionProject/data/questions/reminder.yml#L165-L166

https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/blob/f3f7c54715a30979f0e0dcf3e47c1b928529f0ec/docassemble/MOHUDEvictionProject/data/questions/shared.yml#L992

**Comment by nonprofittechy** [comment]
Maybe migrate to the new reminder system in Assembly Line as well? I didn't realize act of this was copied from MADE

**Comment by miabonardi** [comment]
GBLS in Terms of Use
