### ISSUE TITLE
Failure to attach lease defense should state no attorney fees

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#284]
I think the answer needs to state specifically that the 55.22 violation means that the court cannot award attorney fees.

comment by Courtney Noll

**Comment by tobyfey** [comment]
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/93ab5054-57e8-45f0-83b1-f68906033f3d)

**Comment by tobyfey** [comment]
Add text to answer

Attorney fees may not be awarded due to {{ landlord_doc_name | capitalize }}’s violation of MRCP 55.22.

**Comment by miabonardi** [comment]
This is now in the answer.
