### ISSUE TITLE
Should whether the pleading is available be part of the logic for defense_rent_pleading_requirements?

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#285]
if tenant_got_summons and petition_available:
    if petition_alleges_nonrent or not petition_states_rent_amount or (not has_written_lease and not petition_states_terms_of_lease) or (has_written_lease and not lease_attached and not petition_states_terms_of_lease) or not petition_states_rent_periods or not petition_states_demand_made or (trial_court.circuit == 21 and not petition_separates_nonrent):
      defense_rent_pleading_requirement = True
    else:
      defense_rent_pleading_requirement = False
  else:
      defense_rent_pleading_requirement = None

**Comment by tobyfey** [comment]
also required for 55.22 - no lease attached defense

also, it seems to assume that all the answers to the pleading requirements questions are no if you change from no pleading to pleading, when it should ask again.

**Comment by miabonardi** [comment]
@tobyfey Did you resolve this?
