### ISSUE TITLE
Consider a "short" path and a "long" path

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#291]

**Comment by miabonardi** [comment]
@nonprofittechy can you add more context here? Is this still open or under consideration? I know we do this for discovery, but are we thinking now also for EDDE generally?

**Comment by nonprofittechy** [comment]
I think they were feeling that the tool takes a long time to use, which is true.

The original request was to have an option to skip some of the defenses and have a simple and short path to get to the answer.

I don't know how to do that in a way that makes sense to the tenant or if it's a wise thing for us to build. But it's the request. I think we should check in with them again before executing it.

**Comment by KelizaMcGuire** [comment]
There is not enough time to include this before the end of the project.
