### ISSUE TITLE
Incorporate plain language glossary (already in content dev)

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#302]
Also need to do this for the website (look into Urban Insight's glossary plugin for Wordpress)

**Comment by nonprofittechy** [comment]
Is this it? https://github.com/openadvocate/readclearly

**Comment by tobyfey** [comment]
To use a custom glossary, we need to submit it to OpenAdvocate.  Did we do that before?

**Comment by tobyfey** [comment]
implemented on staging

https://staging7.motenanthelp.org/learns/illegal-eviction-lockout-and-utility-shut-off/

only enabled in learn and resource pages (and looks like it only works in the pages, not in the exceprts in the cards)
defining landlord and tenant every time seems overkill

**Comment by tobyfey** [comment]
Duplicated in other issues, most recent issue - #383
