### ISSUE TITLE
Should case number be optional? id: caption - docket number and file date

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#307]
Especially if tenant says they don't have the summons and petition

**Comment by miabonardi** [comment]
I had this exact thought! Glad to see this issue is here.

**Comment by tobyfey** [comment]
Shawn Caruso said that clerks would be upset if the case number wasn't included. I think it was optional and it was changed at the attorneys' request.

**Comment by miabonardi** [comment]
Re @nonprofittechy in meeting with Terry 9/19 it should be optional
