### ISSUE TITLE
If the question says "you" the answer should say "me", "my" or "I", not repeat "you"

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#309]
Example: 
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7645641/3e76e84d-fd44-4cde-8c4a-11821576cf8b)

id: Petition_introduction

**Comment by ianeis** [comment]
Fixed https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/pull/341
