### ISSUE TITLE
id: pay and stop eviction doesn't say how much court costs are

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#316]
Tenant would need to know the range of court costs (I'm assuming it's the filing fee, not attorneys fee?)

**Comment by tobyfey** [comment]
Glossary term says that court costs are determined by court
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/7767b37d-109a-4600-84a5-4b1ec15315b1)
