### ISSUE TITLE
id: late fees explanation comes after the question. reverse order

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#317]
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7645641/89b01e13-806c-438a-ba39-d36c3861b894)

**Comment by tobyfey** [comment]
Fixed
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/e48354fc-16a2-4804-9a0f-f6699ee6431d)
