### ISSUE TITLE
id: late fees explanation - conditional language in question can be changed to ask if tenant has written lease first

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#318]
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7645641/960c654f-070f-4d5c-98bc-8740ff54aff9)

Current phrasing is awkward and longer to read than necessary

**Comment by motenanthelpissues** [comment]
My problem with this is that I don't know how to make something conditional both on a question answered in the screen - Did your landlord say that you owe fees for paying rent late? and a question previously asked - do you have a written lease?

Right now the conditional only appears if there is no written lease.  So if there is a lease, the question isn't longer than necessary.

I think that's a better solution than asking about the lease again.  We could separate the questions about the lease to another page.

**Comment by tobyfey** [comment]
My problem with this is that I don't know how to make something conditional both on a question answered in the screen - Did your landlord say that you owe fees for paying rent late? and a question previously asked - do you have a written lease?

Right now the conditional only appears if there is no written lease. So if there is a lease, the question isn't longer than necessary.

I think that's a better solution than asking about the lease again. We could separate the questions about the lease to another page.

**Comment by nonprofittechy** [comment]
You can combine `show if variable` with `show if code`

Like:

```
show if:
  variable: abc
  is: True
  code: |
    def == "job"
```

**Comment by tobyfey** [comment]
I couldn't get this to work.  It wouldn't advance the page when there was no lease.
