### ISSUE TITLE
id: estoppel breaches - need explanation of the important or lack of importance of this defense

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#322]
Since this asks tenants a lot of hard questions, we should give them the context to know that it may not be possible to answer without a lawyer, and that it's OK to just answer as well as they know.

See #296 #297 #298

**Comment by motenanthelpissues** [comment]
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/139787221/487bdfff-56e4-4751-adeb-ea048920eb5d)
