### ISSUE TITLE
Consider asking whether user wants instructions for finding answers in summons and case.net in id: how to answer

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#333]
I think it makes sense to explain to the user where they can find the answers up front, which we already basically do on this page for the summons.  We could ask if the user wants instructions for finding the information in the summons and petition, casenet, or both.

If we asked this upfront, we could avoid the interview problems caused by docket_review and make the instructions and pictures for both the summons and casenet conditional in one question block.  Also asking up front would make more sense in directing the tenant to use the name used by the landlord.

**Comment by nonprofittechy** [comment]
I am wondering if it may make more sense to wait to ask about mistakes in the tenant's name until we're first asking about technical defenses. Introducing the idea of having to open a separate website to answer questions may be a bit overwhelming at the beginning of the interview.

**Comment by miabonardi** [comment]
My understanding is this issue is closed and we will keep current location of case.net path
