### ISSUE TITLE
Printing necessary

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#355]
Do we let the user know on the first few screens they need a printer? Do we need to emphasize this more?

"just let the user know before filling out the DIY forms that they will want to print 3 copies (so preferably have a printer and paper ready) or at least have a reliable way to download the copies for future printing."

**Comment by nonprofittechy** [comment]
It's mentioned on the first and second screens. I think this is good as-is...
