### ISSUE TITLE
If attorney is filing out for someone, we currently assume the attorney represents person (no ghostwriting). Is this right?

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#363]

**Comment by miabonardi** [comment]
Sees there is the option to ghostwrite, but in background we disregard?

**Comment by tobyfey** [comment]
The option to ghostwrite is used in the caption.  Maybe I should add something to the notice of hearing to base whether there is an attorney and whether the attorney is ghostwriting?
