### ISSUE TITLE
Improve instructions on "All done" page

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#378]
- [x] * Tell people to fill in the case number if it was left blank
- [x] * Improve language about the certificate of service
- [ ] * Let people know the deadline to file their answer
- [x] * "file at the clerk of court": why not just say "go to the court and bring it to the clerk's office." and we know the address usually
- [x] * explain how to serve the opposing party or their attorney

**Comment by miabonardi** [comment]
@tobyfey @nonprofittechy where does the defendant have to sign? I thought we generate signature for them.

**Comment by miabonardi** [comment]
@tobyfey Do you know the deadline to file the answer or how to figure it out?
