### ISSUE TITLE
Look at the answer's formatting again, with real content

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#379]
* Signature block should have "keep with next"
* Add more space between sections?
* Is the font choice for headings correct? Can we use sans serif?
* Can we align the numbered paragraphs with a hanging indent

**Comment by miabonardi** [comment]
![Screen Shot 2023-09-27 at 3 22 49 PM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/84ff3d97-4e1b-435a-a339-c7970a970610)

**Comment by miabonardi** [comment]
Add keep with next to docs
