### ISSUE TITLE
id: Petition_introduction

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#38]
Remove "introducing" language

Is this in the right spot in the interview?

Make sure bold extends over the full document title(s)

Use the same language -- e.g., "Landlord's petition" or "Summons and Petition for eviction" don't alternate phrasing

**Comment by tobyfey** [comment]
![Screenshot from 2022-12-09 13-44-57](https://user-images.githubusercontent.com/7644783/206771534-852fad8d-8d45-4bc6-b7d1-4d72e18c75c4.png)

**Comment by tobyfey** [comment]
also reduced size of images
