### ISSUE TITLE
Standardize Tenant/I in ud and r+p defenses

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#380]
Looking at an answer with both defenses, I do prefer the first person, but attorneys can file this too

**Comment by nonprofittechy** [comment]
Agreed, on UpToCode we used the phrasing "the tenant" throughout the documents and I think that's the right choice here. No need to make the language conditional in the document.

**Comment by miabonardi** [comment]
Closed
