### ISSUE TITLE
Change color of `help` buttons to not confuse with red asterisk `required`

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#395]
What color is best to change to? Yellow?

![Screen Shot 2023-09-29 at 8 45 56 AM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/2f5aed35-5cdc-435c-b480-dfb39a860b53)

**Comment by miabonardi** [comment]
@nonprofittechy @tobyfey What color would you recommend instead of red here? Yellow? Green? I can ask Stavros to make the change.

**Comment by hamzzy** [comment]
this one has been fixed and the pull request is merged
