### ISSUE TITLE
Add attorney/someone else path language 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#398]
- [x] `id: subsidized housing identification` 
- [x] `id: signpost claims and defenses section`
- [x] `id: notice to terminate`
- [x] `id: lease requirement for notice`
- [x] `id: landlord lied`
- [x] `id: new owner facts for non-class 1 counties`
- [x] `id: estoppel breaches`
- [x] `id: disability`
- [x] `id: defenses explanation`
- [x] `id: signpost service of process`

![Screen Shot 2023-09-29 at 9 11 42 AM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/9b5b27b2-c717-4369-875d-99b4fef2e1d2)

**Comment by miabonardi** [comment]
`id: signpost claims and defenses section`
![Screen Shot 2023-09-29 at 9 08 12 AM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/377982d1-2a33-4d76-8635-ba44e86e26c2)

**Comment by miabonardi** [comment]
id: notice to terminate

**Comment by miabonardi** [comment]
id: new owner facts for non-class 1 counties

**Comment by miabonardi** [comment]
id: estoppel breaches

**Comment by miabonardi** [comment]
id: disability

**Comment by miabonardi** [comment]
id: defenses explanation

**Comment by miabonardi** [comment]
id: signpost service of process

**Comment by nonprofittechy** [comment]
Just wanted to note it's OK to have some generic language too, or to rephrase so we don't need the alternate in every place. Worth considering so we don't have twice as much language to translate in some instances..
