### ISSUE TITLE
What to do if there are no defenses?

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#402]
first, is this likely to happen?

Possible solutions:
 - change text in answer to make it work without defenses
 - encourage reviewing defenses
 - encourage pay or stay
 -

**Comment by miabonardi** [comment]
From Terry:  The answer can merely deny the allegations, and not assert any defenses. The defense "fails to state a valid claim" is probably ok if nothing else is obvious.

**Comment by tobyfey** [comment]
Put conditional language around 
Affirmative Defenses
{{ tenant_doc_name }} requests {{ landlord_doc_name }}’s claims be dismissed because of the following affirmative defenses:
