### ISSUE TITLE
Add defense tied to the tenancy not being terminated yet

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#404]
I don't know why the notice to terminate can't say a later date to terminate the tenancy - maybe that's the defense?  And what good does it do?

![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/2ee34440-6877-4355-934b-dce01f053768)

**Comment by nonprofittechy** [comment]
We don't have a defense tied to the tenancy not being terminated yet, but that's an obvious one to add.

**Comment by miabonardi** [comment]
The tenancy could end in the future so we can remove the validation code
