### ISSUE TITLE
Clarify what service is

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#411]
Someone wrote in the certificate of service block "court" and put the court's address.

Make sure people understand that they need to serve the other party.

**Comment by nonprofittechy** [comment]
Maybe add to the certificate of service a brief explanation of what the CoS is supposed to do.

E.g., the one you file with court must show the service you made on the other party.

**Comment by miabonardi** [comment]
Closed with new instructions to download page
