### ISSUE TITLE
Add more things to interview stats

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#413]
* Did they finish the interview
* Zip
* County
* City
* What forms did they assemble
* When was the interview started
* When did they reach the download page
* Probably almost everything else that is anonymous

**Comment by nonprofittechy** [comment]
See also #556

**Comment by KelizaMcGuire** [comment]
City and county stat tracking has been added in #583. Zip and "did they finish the interview" stat tracking already exists in the interview.
