### ISSUE TITLE
Upload resources to website

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#434]
[FORM CV 95 Wages HoH Exemption claim MOSC.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EfpUPTCqAxpAuGsQ2uFJM8wBOcmpaJ7kB59xN3ixYjNUTQ)
[FORM CV 96 Judgment Debtors Claim for Exemption MOSC.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EYfRdeEPpDVAlEEQtKvwcYsBINr8E8_32AzLKNoPddz2zA)
[Gude to Repairs to a Rental Unit LSMO 2018.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EdNvJWxwcyFMiGlU0bUsv34BRvScCA7oqYt93z-NtbPLvQ)
[Guide to Foreclosure of Rental Unit LSMO 2019.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/Ef7VCqOSLmhFsdrzhL4IsfUBIVERkCXlUm9OMOObiOOZQQ)
[Guide to Landlord Tenant Duties and Rights LSMO 2018.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/Ed5vUM6O9TBMkctDnmmM1H8B38rnoKYhdoLkAyrUikNoJQ)
[Guide to Repair and Deduct LSMO 2018.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EW81ubdWnYBDqLS8ojCHyIoBfqFQVQC55JeEzIkz9DfaTQ)
[Guide to Representing Yourself when Facing Eviction ArchCity.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EU-7_o8qmBJJprWj4qT7I_UBI_6hEnaacyy35hWNijjLwg)
[Guide to Sale of the Rental Unit LSMO 2018.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EY6Zphs7oNFHtkRS_KdRxK8BjYyIH6n4N3gDjiDpe9f-Mw)
[Guide to Security Deposits LSMO 2018.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/ERYoLNDwWTxHuHh8jtmhNpUBAP9alIOCWeF4bXATtvkCfQ)
[Guide to Small Claims Court LAWMO.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EZPcDITGYMJOmZnnlekQnB4B9_0CnGzaJaYGpcwURqczVw)
[Guide to Tenant Abandonment LSMO.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/Ef17DBaL7yRPrgUMfrueLPMBU4hxSlQwvlAsTMTUhH_rfQ)
[Guide to Tenant Self Representation.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EQB9JAVcglRHuN5gUxlv89kBpXVAKEN319I0Kqcpj8Yhtg)
[Handbook - You and Your Landlord LSEM.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EWL-zeDYmB1Lpx6ejsvd500BYHkQGT9DYX88_jZj6dFGLQ)
[PPT Preventing Eviction.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EefjduBEbHpDoZoQXdjKRi0B8jURCoVWOtu3dm4iBwI1SQ)
[PPT Representing Tenants in Evictions.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EaQstDclnXZBs2KgP8anYeYBWZZatGTMyEwP91QxFFKlwA)
[Sample Court Docket Assoc. Cir. STL Co. Div. 43.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/EbvY4_8wPmtLqeZojr38ua8B6NgvfbrVBDqMQDoGefMYFA)
[Sample Court Docket Small Claims STL Co. Div. 43.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/ESXUggX1qktApKDSHorGfQsBEwzingF6Q8n1PVXxUG_agg)
[Sample Preparing Trial Exhibits with scanner app.pdf](https://lsem-my.sharepoint.com/:b:/g/personal/tllawson_lsem_org/ETrgwst9o7ZGuUyvyBkV6sABPU9OE4bkgF9v_8rBQnSwVQ)

**Comment by miabonardi** [comment]
For uploads to site ready to go into resources, see this folder in the shared Teams site:
Content Dev\Content - Draft\0 UPLOADS

**Comment by tobyfey** [comment]
Uploaded to staging9, plus additional documents sent by Victoria St. Jean

Unpublished Guide to Landlord Tenant Duties and Rights LSMO 2018.pdf because multiple commenters pointed out it is the same as You and Your Landlord, with less info.
