### ISSUE TITLE
Notice different for abandonment 

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#436]
Should we add this to the terms? 

From Terry: For abandonment, Landlord must post and send notice by regular mail and certified mail notice before assuming tenant abandoned and removing property. See 441.065

https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/blob/fa0eb2d8e541ec2f1078018958bd4bc2672dd9c1/docassemble/MOHUDEvictionProject/data/questions/autoterms.yml#L4-L7

**Comment by tobyfey** [comment]
Abandonment not used in the interview to define by autoterms, so this issue isn't relevant.
