### ISSUE TITLE
Explain sooner which docs may be included, including which motions

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#444]

**Comment by tobyfey** [comment]
I'll do this as part of the integrating more of the motions into the interview.

**Comment by nonprofittechy** [comment]
This might be a good best practice to document in our style guide

**Comment by miabonardi** [comment]
About this interview page, second page

**Comment by miabonardi** [comment]
Potentially a display template?
