### ISSUE TITLE
Website resources - DIY Forms should show up for every county not just statewide

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#445]

**Comment by tobyfey** [comment]
"3. Is there a way to automatically make ""Statewide"" a selection for each search, so people don't miss out on those resources if they forget to select it or don't read the description?
"
Sarah Freimiller, MoTenantHelp.org Resources - edits and additions(1-7).xlsx

**Comment by tobyfey** [comment]
Sarah made this comment, and will most likely be the one to maintain it, so I could show her how to add every county as a tag to every state.
But it also seems like there should be a way to reverse the parent-child relationship.

**Comment by tobyfey** [comment]
We are using a list of every county with statewide to fix this.  This can be done easily with airtable
