### ISSUE TITLE
Why is there an "I agree" button on `id: how to answer`?

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#453]
Unclear to me what we are asking user to agree to on this page

![Screen Shot 2023-11-20 at 12 45 36 PM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/507e4580-6bfc-4a0c-a1a2-fb0843e1ec78)

**Comment by miabonardi** [comment]
@nonprofittechy @tobyfey Should this be a "Next" or "Continue" button?

**Comment by nonprofittechy** [comment]
We used "I agree" in MADE after some thought. I think we considered and decided against "I understand" because it wasn't a fair thing to assume people did at this point.

I do think it's okay to have it not say "Next" in this one case. It's the kickoff to the interview.

**Comment by nonprofittechy** [comment]
@carorob might have thoughts. I'm sure I discussed this with her on MADE back in 2018
