### ISSUE TITLE
Increase spacing on review screen

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#459]

**Comment by miabonardi** [comment]
@nonprofittechy can you advise on what specifically needed to change here

**Comment by nonprofittechy** [comment]
top margin, so that it is easier to visually tell that the headings indicate separate content.

**Comment by tobyfey** [comment]
This was fixed by the accordion blocks
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/aabad7d6-f020-4f99-b47d-06189914f6b2)
