### ISSUE TITLE
Add instructions about where to find filing date (if needed?)

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#487]
![image](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/41758f86-56e3-4b7e-bfd4-445cfc52be15)

Is this needed in a rent and possession case?

**Comment by KelizaMcGuire** [comment]
Fixed in #599
