### ISSUE TITLE
User requested help by asking for developer permissions

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#490]
![Screen Shot 2023-12-20 at 10 53 05 AM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/59e55bac-b325-4242-9a00-9ee97143b06a)

I think this may be someone looking for help with the interview? Is there a way to disable "Request developer account" from the User settings? Maybe we need to add the Feedback to every page? 

![Screen Shot 2023-12-20 at 10 50 02 AM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/7333cc1b-ab6b-479a-8b6d-d08f3ecafe79)

**Comment by miabonardi** [comment]
@nonprofittechy Is there a way to disable "Request developer account" from the User settings?

**Comment by nonprofittechy** [comment]
https://docassemble.org/docs/config.html#user%20can%20request%20developer%20account

**Comment by KelizaMcGuire** [comment]
Fixed.
