### ISSUE TITLE
ID new owner facts for class 1 counties: 
User feedback: something
(`notice_contains_sale_document`)

### ISSUE THREAD

**Issue by LemmaLegal** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#501]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `new owner facts for class 1 counties`
Details | Did your landlord ever sell the house while you were living at this address:

I am unable to select Yes and then "I don't know" about the letter. Each time I tried there was a quick refresh and then "I don't know" was deselected. It progressed normally when I selected "No" regarding the letter.
Variable being sought | `notice_contains_sale_document`
Package version | `1.5.5`
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by miabonardi** [comment]
Just tested this on Mac and Chrome browser and had no issue, will leave open

**Comment by tobyfey** [comment]
Tested, no issue
