### ISSUE TITLE
For Discovery: Trigger Motions based on summons/hearing date

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#502]
When is your next summons/hearing date?
- If after today → Motion to Continue
- If after today + requesting discovery → Motion to Continue AND Motion to Shorten the Time to Respond to Defendant's First Interrogatories and/or Requests for Production and/or Requests for Admission

**Comment by tobyfey** [comment]
I understood this as if it's less than 30 days, then the user needs to do either a motion to continue (because then there would be more than 30 days to respond) or a motion to shorten time (asking the court to order the landlord to respond in less than 30 days, in time for the trial).
If it was more than 30 days, it's not necessary.

But is this part of the motion tester or the discovery/eviction interview?

**Comment by miabonardi** [comment]
Updated! You are correct-Thank you!

**Comment by miabonardi** [comment]
It's a part of EDDE (Answer/Discovery/Motions).

**Comment by miabonardi** [comment]
Not for motion tester

**Comment by miabonardi** [comment]
Motion to shorten time is automated in motion tester and needs to be incorporated into EDDE

**Comment by miabonardi** [comment]
Default to motion to continue or do we need to also have shorten time? Could we do motion to continue or in the alternative shorten time?

@tobyfey checking in with LSEM team

**Comment by miabonardi** [comment]
If they choose to do discovery, this is adding motions.

This might not be necessary per @tobyfey because motion to continue is being triggered if trial date is anytime after today.

**Comment by miabonardi** [comment]
@tobyfey motion to continue is triggered based on hearing date, not trial date 

https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/blob/a884d5bf5249d888202ba4784b716839a5da0518/docassemble/MOHUDEvictionProject/data/questions/MOHUDEvictionProject.yml#L491-L496

https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/blob/a884d5bf5249d888202ba4784b716839a5da0518/docassemble/MOHUDEvictionProject/data/questions/shared.yml#L411-L415
