### ISSUE TITLE
Duplicate question for `eviction_reason` ?

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#523]
When looking for `eviction_reason`, `id: case type from summons` takes priority because it is lower referenced in file than `id: reason for eviction` 

Are both of the versions of this question used, or just the second one? I need help understanding when each version is used and why we have two versions. We should add comments above each question explaining why we have both if both are used. 

https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/blob/386255ffdfc221993ccda102e8b45952a5cc66c1/docassemble/MOHUDEvictionProject/data/questions/court_information.yml#L54-L299

**Comment by tobyfey** [comment]
You're right, I don't think `id: reason for eviction` is used. I think at one time those question may have had `if: `conditions based on casenet and having the summons.
