### ISSUE TITLE
Undefined conditional variables after edit?

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#525]
After I changed tenant_has_disability from True to False, one of the questions that is no longer applicable still appears on the screen. 
![Screenshot_20240222-140650](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/7665ea62-79c9-4462-9f31-3c69d583017d)
I can fix this problem by changing the show if, but the no longer applicable answers still show up on the review screen
![Screenshot_20240222-141513](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/d66ad827-97ee-47ac-a221-2a08e0bb8b47)
Can/should we undefine conditional variables?

**Comment by miabonardi** [comment]
Interesting! Will need @nonprofittechy to answer here

**Comment by nonprofittechy** [comment]
@tobyfey this is a situation that happens with long interviews that have review screens, pretty commonly.

I don't recommend deleting and undefining variables. I've tried that before and it becomes pretty unwieldy. Instead, I suggest wrapping any mention of those conditionally defined variables inside an `if` statement. It takes more work but is safer and more reliable.
