### ISSUE TITLE
Why is day on notice limited to today or before?

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#528]
A tenant could receive a notice with a notice that says you must leave by a date in the future. (In contrast to other date on this question, which does make sense to limit to today or in the past)
![Screenshot_20240222-162127](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/7644783/68d1b060-e7c8-47ef-86e4-00352bd1f57b)

**Comment by miabonardi** [comment]
I agree about removing  `max: ${ today().format("yyyy-MM-dd") } ` from line 1289 but not from 1264

https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/blob/386255ffdfc221993ccda102e8b45952a5cc66c1/docassemble/MOHUDEvictionProject/data/questions/defense_logic.yml#L1217-L1291
