### ISSUE TITLE
EDDE does not fully incorporate the motions

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#543]
In the currently live version, because skip undefined is on, the motions generated by EDDE right now have missing variables. The individual motion interview orders are not run. 

We need to add something like this:
```
  if wants_discovery and not original_hearing_date_past: 
    motion_to_shorten_time_order
   
  if original_hearing_date_past:
    motion_for_leave_to_file_order
```

Will wait for https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/pull/541 to be merged because the motion file was renamed and want to avoid conflicts.

**Comment by tobyfey** [comment]
We should add those questions to the review block too.

**Comment by miabonardi** [comment]
I was thinking for now we could add it after Discovery just to get them completed. What do you think? We might be able to also reference the motion specific review screens in the file_a_motion.yml.

**Comment by miabonardi** [comment]
file_a_motion.yml has `enable_al_nav_sections = True` in it and if I include file_a_motion.yml in MOHUDEvictionProject.yml it overrides the entire interview. Setting `enable_al_nav_sections = False` doesn't fix it

**Comment by tobyfey** [comment]
The Motion to Set Aside Judgment requires a final judgment to be made, which isn't really asked in the initial hearing.  Should we ask this?  Is it the same as somebody entering a hearing date in the past?
