### ISSUE TITLE
Are we still using "DIY Forms"?

### ISSUE THREAD

**Issue by miabonardi** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#544]
![Screen Shot 2024-03-01 at 4 32 49 PM](https://github.com/LemmaLegalConsulting/docassemble-MOHUDEvictionProject/assets/65858862/7ae522e4-d64a-42e7-9f49-64ea5a710e53)

**Comment by tobyfey** [comment]
Fixed in https://staging11.motenanthelp.org/resources/

Also updated permalink from https://staging11.motenanthelp.org/resources/diy-form-motion-to-continue/ to https://staging11.motenanthelp.org/resources/edde-form-motion-to-continue/

Will close this issue when website main site is updated
