### ISSUE TITLE
Get intake criteria from all statewide legal aid programs

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#570]
Start with housing and consumer matters

Copy Terry Lawson, be ready to follow-up after a week especially since this is a short week.

**Comment by KelizaMcGuire** [comment]
Emailed Terry Lawson for the intake criteria for LSEM housing and consumer units. Got an out of office till July 9th auto-reply.

Do you have the contact info for the other MO legal aid orgs or should I reach out to ask for them?

**Comment by KelizaMcGuire** [comment]
We have Housing and Consumer Law intake criteria from:

- [X] LSEM
- [X] MMLS
- [ ] LSSM
- [ ] LAWMO

**Comment by KelizaMcGuire** [comment]
All intake criteria have been received and forwarded to Toby and Quinten.
