### ISSUE TITLE
Add explanations and examples to Motion to file

### ISSUE THREAD

**Issue by tobyfey** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#581]
- [ ] About your case: “Which motions do you need?”: Should we add descriptions to the motion types?
- [ ] General 	Should we add an explanation of what consent from the landlord means to all questions asking if they have given consent?
- [ ] Your motions: Motion for Leave to File Responsive Pleadings: “Was there a reason you couldn’t get your response ready and file it on time?” 	Should we add examples?
- [ ] Your motion: Motion to Shorten Time: “Do you have any unfair reasons for making this request?” 	Should we add an explanation for what is an unfair reason?
- [ ] Your motion: Motion to Set Aside Judgement: "Why should the judge agree to cancel the earlier decision because of your request?" 	Should we provide examples here?

**Comment by tobyfey** [comment]
from #574

**Comment by tobyfey** [comment]
Toby will write an email asking for examples and explanations from LSEM

**Comment by KelizaMcGuire** [comment]
Closing this issue because it has been split into #604, #605, #606, #607, and #608 for future development by the LSEM team if they wish to add more examples/explanations.
