### ISSUE TITLE
Test and cleanup the reminder feature

### ISSUE THREAD

**Issue by nonprofittechy** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#627]
- It says text, but we're not texting anyone
- Does it work and should it be used if it's just a reminder to file the documents?
- Does it need to be enabled -- there's an assembly line feature that we're trying to invoke. but is it getting used?
- Is it redundant since Case.net has the same feature?

**Comment by KelizaMcGuire** [comment]
#366

**Comment by KelizaMcGuire** [comment]
#366
