### ISSUE TITLE
ID Petition_introduction: 
User feedback: language
(`tenant_got_summons`)

### ISSUE THREAD

**Issue by LemmaLegal** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#79]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Petition_introduction`
Details | personal service should be a service option.
Variable being sought | `tenant_got_summons`
Package version | `1.0`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/issues/56

https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/issues/80

**Comment by tobyfey** [comment]
Changed the options to:

      - "By mail": mail
      - "It was taped, stapled, or posted to my door or home": posting
      - "It was delivered by the sheriff": sheriff
      - "It was delivered by the landlord or somebody other than the sheriff": personal

**Comment by tobyfey** [comment]
added an explanation to the sheriff option calling it personal service

**Comment by tobyfey** [comment]
also added certified mail
