### ISSUE TITLE
ID any other opposing parties: 
User feedback: something
(`other_parties.there_is_another`)

### ISSUE THREAD

**Issue by LemmaLegal** [LemmaLegalConsulting/docassemble-MOHUDEvictionProject#81]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `any other opposing parties`
Details | May want to consider adding something about LLCs/corporations not represented by an attorney, although that may be beyond what this form can do.
Variable being sought | `other_parties.there_is_another`
Package version | `1.0`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
This is included as a defense and can be explained in #198
